version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Analogy.LogViewer.Template
    versions:
    - 1.8.1.1
    - 1.8.1.3
    - 1.8.3.1
  - dependency-name: Analogy.LogViewer.Interfaces
    versions:
    - 2.10.0
    - 2.10.2
    - 2.11.0
    - 2.12.1
